### PR TITLE
Update assets to latest bower package and restructure files

### PR DESCRIPTION
**Pull request by joshreeves**
This imports the latest changes to the bower package (supporting default content), and also restructures the gem assets to support the new JS config via server-side variable.

@jedmurdock

### CODE REVIEW

**Comment by jedmurdock** [comment]
why does the cedar version in bower not match the one in version.rb?

**Comment by joshreeves** [comment]
@jedmurdock Because the bower package was started a lot later. I suppose I could advance it to match. I'll do that next time. :)

**Comment by jedmurdock** [comment]
it's up to you, i just don't get how they could work if they don't match. also, up to you as to when to remove the 'pre' tag (and then reset versioning to 1.0.0 i suppose) :+1:

**Comment by joshreeves** [comment]
@jedmurdock It's because the bower package and the gem aren't related, other than the gem contains the bower package. So the gem is at version x, but the bower package is at version y

**Comment by jedmurdock** [comment]
right - thanks

**Pull request merged**
